<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Portfolio</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <!-- Sidebar -->
    <div class="bg-light border-right" id="mySidebar">
        <button onclick="w3_close()" class="btn btn-primary w-100 mb-2">Close &times;</button>
        <a href="#" class="list-group-item list-group-item-action">Home</a>
        <a href="#about" class="list-group-item list-group-item-action">About</a>
        <a href="#projects" class="list-group-item list-group-item-action">Projects</a>
        <a href="#contact" class="list-group-item list-group-item-action">Contact</a>
    </div>

    <!-- Page Content -->
    <div id="main">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <button class="btn btn-primary" onclick="w3_open()">☰ Open Sidebar</button>
                <a class="navbar-brand ms-3" href="#">My Portfolio</a>
            </div>
        </nav>

        <!-- Header Section -->
        <header class="text-white text-center py-5" style="background-image: url('img/Screenshot\ \(54\).png'); background-size: 100%;">
            <div class="container">
                <h1>Welcome to My Portfolio</h1>
                <p class="lead">Muhammad Chairawan | XI RPL 3</p>
            </div>
        </header>


        <!-- About Section -->
        <section id="about" class="py-5">
            <div class="container">
                <h2 class="text-center">About Me</h2>
                <div class="row py-1">
                    <div class="col-md-6 text-center">
                        <p>As a front-end developer in class XI RPL 3, I was responsible for developing the user interface (UI) for the web application we generated in the learning environment.
                            (UI) for the web applications generated by us in the learning environment. In this context
                            In this context, I am one of the students who have a role in developing and maintaining our class website or application.
                            our class application.<br>

                            My tasks include designing the interface, coding the front-end elements using HTML, CSS, and
                            JavaScript, as well as ensuring that the web application is responsive and fits the learning needs.
                            learning needs. I work closely with other members of the development team in integrating the front-end design with the developed functionality.
                            design with the functionality developed by other students in the class.</p>
                    </div>
                    <div class="col-md-6 text-center">
                        <img src="img/Charawan1.png" class="img-fluid rounded-circle" alt="Profile Picture" style="max-width: 500px;">
                    </div>
                </div>
            </div>
        </section>

        <!-- Projects Section -->
        <section id="projects" class="py-5 bg-light">
            <div class="container">
                <h2 class="text-center">My Activity</h2>
                <div class="row py-1">
                    <!-- Project 1 -->
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img src="img/Screenshot (134).png" class="card-img-top" alt="Project 1">
                            <div class="card-body">
                                <h5 class="card-title">BloodStrike</h5>
                                <p class="card-text">This is my progress bloodstrike.</p>
                            </div>
                        </div>
                    </div>
                    <!-- Project 2 -->
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img src="img/Screenshot (137).png" class="card-img-top" alt="Project 2">
                            <div class="card-body">
                                <h5 class="card-title">DuoLingo</h5>
                                <p class="card-text">This is my progress learning japanese from duolingo.</p>
                            </div>
                        </div>
                    </div>
                    <!-- Project 3 -->
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img src="img/Screenshot (138).png" class="card-img-top" alt="Project 3">
                            <div class="card-body">
                                <h5 class="card-title">Roblox</h5>
                                <p class="card-text">This is my friend in roblox.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Contact Section -->
        <section id="contact" class="py-5">
            <div class="container">
                <h2 class="text-center">Contact Me</h2>
                <form action="koneksi.php" method="POST">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="3" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Send</button>
                </form>
            </div>
        </section>

        <!-- Messages Section -->
        <section id="messages" class="py-5 bg-light">
            <div class="container">
                <h2 class="text-center">Messages</h2>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Message</th>
                                <th>Received At</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $servername = "localhost";
                            $username = "root"; // ganti dengan username database Anda
                            $password = ""; // ganti dengan password database Anda
                            $dbname = "portfolio";

                            // Buat koneksi
                            $conn = new mysqli($servername, $username, $password, $dbname);

                            // Cek koneksi
                            if ($conn->connect_error) {
                                die("Connection failed: " . $conn->connect_error);
                            }

                            // Query untuk mengambil data
                            $sql = "SELECT name, email, message, created_at FROM messages ORDER BY created_at DESC";
                            $result = $conn->query($sql);

                            if ($result->num_rows > 0) {
                                while ($row = $result->fetch_assoc()) {
                                    echo "<tr>";
                                    echo "<td>" . $row['name'] . "</td>";
                                    echo "<td>" . $row['email'] . "</td>";
                                    echo "<td>" . $row['message'] . "</td>";
                                    echo "<td>" . $row['created_at'] . "</td>";
                                    echo "</tr>";
                                }
                            } else {
                                echo "<tr><td colspan='4' class='text-center'>No messages found</td></tr>";
                            }
                            $conn->close();
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

        <!-- Footer -->
        <footer class="bg-light py-4">
            <div class="container text-center">
                <p>&copy; 2024 My Portfolio. All Rights Reserved.</p>
            </div>
        </footer>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>
    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
</body>

</html>